sudo: required
dist: trusty
language: cpp
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      - libsdl2-dev
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl2; fi
script:
  - ./grim new foo
  - (cd foo; ../grim build)
